version: '3.8'
services:
  spoolman:
    image: donkie/spoolman:test
    environment:
      - SPOOLMAN_LOGGING_LEVEL=INFO
  tester:
    image: donkie/spoolman-tester:latest
    volumes:
      - ./tests:/tester/tests
    depends_on:
      - spoolman
