[project]
name = "Spoolman"
description = "A web service that keeps track of 3D printing spools."
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"
license = {text = "AGPL-3.0-only"}
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = [""]
exclude = ["client"]

[tool.ruff]
select = ["ALL"]
ignore = ["A003", "D101", "D104", "D406", "D407", "S104", "TRY201", "TRY003", "EM101", "EM102", "DTZ003", "PLR0913"]
line-length = 120
target-version = "py39"

[tool.ruff.per-file-ignores]
"tests*/*" = ["ANN201", "S101", "PLR2004"]
"migrations/versions/*" = ["N999"]

[tool.black]
line-length = 120
target-version = ['py39']

[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
spoolman_docs = "spoolman.docs:generate_docs"
