name: Integration Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install pre-commit==3.3.2
      - run: pre-commit run --all-files
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Spoolman
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: donkie/spoolman:test
          outputs: type=docker,dest=/tmp/spoolman.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spoolman
          path: /tmp/spoolman.tar
  build-tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Spoolman Tester
        uses: docker/build-push-action@v4
        with:
          context: ./tests_integration
          tags: donkie/spoolman-tester:latest
          outputs: type=docker,dest=/tmp/spoolman-tester.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spoolman-tester
          path: /tmp/spoolman-tester.tar
  tests:
    needs: [build, build-tester]
    strategy:
      matrix:
        dbtype: ["postgres", "sqlite", "mariadb", "cockroachdb"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download built images
        uses: actions/download-artifact@v3
        with:
          path: /tmp
      - name: Load images
        run: |
          docker load --input /tmp/spoolman/spoolman.tar
          docker load --input /tmp/spoolman-tester/spoolman-tester.tar
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./tests_integration/docker-compose-${{ matrix.dbtype }}.yml"
          up-flags: "--abort-on-container-exit"
          down-flags: "--volumes"
